### ISSUE TITLE
Vybrat preferované hodnoty dat sloučených výrobců

### ISSUE THREAD

**Issue by jindrichmynarz** [KIZI/antigen-covid-tests-knowledge-graph#16]
Po sloučení výrobců (#14) mohou získat jejich vlastnosti více hodnot. V případě, kdy pro vlastnost očekáváme maximálně 1 hodnotu (např. `sh:maxCount 1` pro `schema:name`) bychom měli implementovat způsob výběru preferované hodnoty. Například jde o názvy "SD Biosensor, Inc" a "SD BIOSENSOR" pro výrobce s ID = 854.

**Comment by jindrichmynarz** [comment]
Tohle bychom mohli vyřešit normalizací jmen výrobců dle #18 v SPARQL Update pro post-processing.

**Comment by hank05-vse** [comment]
Myslím, že co se týče jmen výrobců, tak bychom mohli používat pouze jména z elementu `<euList>`, tam kde tento element je. Tam kde není, tak bychom použili jméno výrobce z elementu '<vyrobce>. Myslím, že u výrobce není nutné mít více jmen.

**Comment by jindrichmynarz** [comment]
Vyřešeno v #27.
