### ISSUE TITLE
Návrh CQ, která porovnává testy od jednoho výrobce

### ISSUE THREAD

**Issue by hank05-vse** [KIZI/antigen-covid-tests-knowledge-graph#25]
CQ19 Choose at least two tests that come from one given manufacturer. Which of these tests has higher sensitivity for high viral load tested by PEI?

_Originally posted by @hank05-vse in https://github.com/jindrichmynarz/antigen-covid-tests-knowledge-graph/pull/21#discussion_r1123847349_

**Comment by jindrichmynarz** [comment]
V  57ed75df08ffa7761ffc9a10baf9aebee5d746a6 jsem přidal CQ porovnávají testy dle výrobce. Můžeme přidat další CQ, nebo toto téma uzavřít.

**Comment by hank05-vse** [comment]
> Proč myslíš? Test právě má ověřit, jestli postup slučování výrobců funguje.

Protože nyní nám takto naimplementovaná otázka nevyhodí chyby a my víme, že to sloučení výrobců zatím nefunguje na 100 %. Proto mě zajímalo, jestli by šlo za výrobce dosadit přímo nějaké konkrétní výrobce, které jsou zástupci těch tří skupin (z dokumentu na Drivu), kde víme, že sloučení ještě neproběhlo. Tak abychom při řešení sloučení výrobců mohli postupně ověřovat, zda nám to už opravdu funguje tak jak má, a že se sloučili všichni výrobci.

**Comment by jindrichmynarz** [comment]
Tato CQ nám nevrací chybu, protože jsem chybu generování neunikátních IRI výrobců opravili. Je pravdou, že duplicita výrobců není opravena úplně, protože jsme opravili jen tu, kterou jsme chybou v transformaci vytvářeli sami. Neopravili jsme ale zcela všechnu duplicitu výrobců ve zdrojových datech vyjma #17. Úplnou deduplikaci nám ale žádná kompetenční otázka nepotvrdí.

**Comment by hank05-vse** [comment]
Ok, v tom případě máme toto issue hotové.
